In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("neet_data.csv")

In [3]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [4]:
dff= pd.DataFrame(df)

In [8]:
dff

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [16]:
df_sort=dff.sort_values("retweet_count",ascending=False)

In [10]:
df_sort.head

<bound method NDFrame.head of                 created_at  retweet_count               source  \
32860  2020-11-08 05:30:01         614304   Twitter for iPhone
33262  2020-11-07 21:52:54         581097  Twitter for Android
35111  2020-11-06 14:20:33         381458      Twitter Web App
32585  2020-11-08 07:19:02         204348   Twitter for iPhone
38044  2020-11-04 18:19:13         192350   Twitter for iPhone
...                    ...            ...                  ...
33534  2020-11-07 16:45:39              0      Twitter Web App
33533  2020-11-07 16:46:12              0   Twitter for iPhone
13611  2020-10-27 01:23:03              0  Twitter for Android
33531  2020-11-07 16:48:10              0  Twitter for Android
47380  2020-10-30 15:28:14              0  Twitter for Android

                   user_id                                          user_name  \
32860  1024658968394625024               \xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3
33262  1099388669448867842                           Neet\xf0\x9f\x83\x8fPeet
35111           2578241503  \xe3\x81\xaf\xe3\x81\xaa\xe3\x81\x91\xe3\x81\x...
32585  1103362192169189376                                       Parneet kaur
38044             54249914                                       Couture_Neet
...                    ...                                                ...
33534  1301196667887038464  \xe0\xae\xaa\xe0\xae\xbe\xe0\xae\x9c\xe0\xae\x...
33533           2835488103      Praise be to Hibiki (Thanks be to Symphogear)
13611  1207560622273159169                                      sochkpostkaro
33531   905021614546313216                                        Indore Talk
47380  1211810532006612992                                             Icarus

                                        user_description  user_follower_count  \
32860  \xe3\x85\xa4\xe3\x82\xa2\xe3\x82\xa4\xe3\x82\x...                   62
33262  \xe2\x96\xa0\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\x...                   11
35111  Kei|20\xe2\x86\x91|intp|eng/fil OK|SparQlew\xe...                  624
32585  \xf0\x9f\x96\x95 all negative , all positive v...                  587
38044                         snapchat . Neetsobeautiful                  547
...                                                  ...                  ...
33534                               Indian,BJP supporter                   11
33533  Blessed be the name of Hibiki\nBuilt a new DnD...                 1324
13611                            Janta ki awaz uthayenge                   24
33531  Indore Talk is City's First Hyperlocal Infotai...                 5031
47380  404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...                   16

       user_friends_count               user_location  user_verified  \
32860                 115                         NaN          False
33262                 141                         NaN          False
35111                 527  read carrd before follow!!          False
32585                 193             New Jersey, USA          False
38044                1182                 Miii Casaa           False
...                   ...                         ...            ...
33534                  37                 Tirunelveli          False
33533                4252     Ha ha! Time for ethics!          False
13611                 164                         NaN          False
33531                  25               Indore, India          False
47380                  45    your friendly local enby          False

                      user_url  \
32860  https://t.co/cHZdP4uOdu
33262                      NaN
35111  https://t.co/XgmHbPUgAi
32585  https://t.co/PXgYJf0gIA
38044                      NaN
...                        ...
33534                      NaN
33533                      NaN
13611                      NaN
33531  https://t.co/41cPZozsD8
47380                      NaN

                                                   tweet  length_of_tweet
32860  RT @JoeBiden: America, I\xe2\x80\x99m honored ...              140
33262  RT @KamalaHarris: We did it, @JoeBiden. https:...               63
35111  RT @GretaThunberg: So ridiculous. Donald must ...              140
32585  RT @Al_Sanchino: It\xe2\x80\x99s wild Trump su...              140
38044  RT @JoeBiden: Keep the faith, guys. We\xe2\x80...               57
...                                                  ...              ...
33534  @mosquitomani @vishnuuparam @onandi143 When Bj...              140
33533  @FallerHunter03 @icypika @ooo_thank @HerShinin...              140
13611  @Imritik_ @Swamy39 @theicai Galat insan ko tag...              140
33531  #FeaturedTalk: Prepare with the Subject Expert...              140
47380  i hate talking to people from my department bu...              139

[47381 rows x 13 columns]>

In [18]:
df_sort.value_counts

<bound method DataFrame.value_counts of                 created_at  retweet_count               source  \
32860  2020-11-08 05:30:01         614304   Twitter for iPhone
33262  2020-11-07 21:52:54         581097  Twitter for Android
35111  2020-11-06 14:20:33         381458      Twitter Web App
32585  2020-11-08 07:19:02         204348   Twitter for iPhone
38044  2020-11-04 18:19:13         192350   Twitter for iPhone
...                    ...            ...                  ...
33534  2020-11-07 16:45:39              0      Twitter Web App
33533  2020-11-07 16:46:12              0   Twitter for iPhone
13611  2020-10-27 01:23:03              0  Twitter for Android
33531  2020-11-07 16:48:10              0  Twitter for Android
47380  2020-10-30 15:28:14              0  Twitter for Android

                   user_id                                          user_name  \
32860  1024658968394625024               \xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3
33262  1099388669448867842                           Neet\xf0\x9f\x83\x8fPeet
35111           2578241503  \xe3\x81\xaf\xe3\x81\xaa\xe3\x81\x91\xe3\x81\x...
32585  1103362192169189376                                       Parneet kaur
38044             54249914                                       Couture_Neet
...                    ...                                                ...
33534  1301196667887038464  \xe0\xae\xaa\xe0\xae\xbe\xe0\xae\x9c\xe0\xae\x...
33533           2835488103      Praise be to Hibiki (Thanks be to Symphogear)
13611  1207560622273159169                                      sochkpostkaro
33531   905021614546313216                                        Indore Talk
47380  1211810532006612992                                             Icarus

                                        user_description  user_follower_count  \
32860  \xe3\x85\xa4\xe3\x82\xa2\xe3\x82\xa4\xe3\x82\x...                   62
33262  \xe2\x96\xa0\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\x...                   11
35111  Kei|20\xe2\x86\x91|intp|eng/fil OK|SparQlew\xe...                  624
32585  \xf0\x9f\x96\x95 all negative , all positive v...                  587
38044                         snapchat . Neetsobeautiful                  547
...                                                  ...                  ...
33534                               Indian,BJP supporter                   11
33533  Blessed be the name of Hibiki\nBuilt a new DnD...                 1324
13611                            Janta ki awaz uthayenge                   24
33531  Indore Talk is City's First Hyperlocal Infotai...                 5031
47380  404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...                   16

       user_friends_count               user_location  user_verified  \
32860                 115                         NaN          False
33262                 141                         NaN          False
35111                 527  read carrd before follow!!          False
32585                 193             New Jersey, USA          False
38044                1182                 Miii Casaa           False
...                   ...                         ...            ...
33534                  37                 Tirunelveli          False
33533                4252     Ha ha! Time for ethics!          False
13611                 164                         NaN          False
33531                  25               Indore, India          False
47380                  45    your friendly local enby          False

                      user_url  \
32860  https://t.co/cHZdP4uOdu
33262                      NaN
35111  https://t.co/XgmHbPUgAi
32585  https://t.co/PXgYJf0gIA
38044                      NaN
...                        ...
33534                      NaN
33533                      NaN
13611                      NaN
33531  https://t.co/41cPZozsD8
47380                      NaN

                                                   tweet  length_of_tweet
32860  RT @JoeBiden: America, I\xe2\x80\x99m honored ...              140
33262  RT @KamalaHarris: We did it, @JoeBiden. https:...               63
35111  RT @GretaThunberg: So ridiculous. Donald must ...              140
32585  RT @Al_Sanchino: It\xe2\x80\x99s wild Trump su...              140
38044  RT @JoeBiden: Keep the faith, guys. We\xe2\x80...               57
...                                                  ...              ...
33534  @mosquitomani @vishnuuparam @onandi143 When Bj...              140
33533  @FallerHunter03 @icypika @ooo_thank @HerShinin...              140
13611  @Imritik_ @Swamy39 @theicai Galat insan ko tag...              140
33531  #FeaturedTalk: Prepare with the Subject Expert...              140
47380  i hate talking to people from my department bu...              139

[47381 rows x 13 columns]>

In [ ]:
df.