In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("neet_data.csv")

In [3]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [4]:
dff= pd.DataFrame(df)

In [5]:
dff

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [6]:
df_sort=dff.sort_values("retweet_count",ascending=False)

In [7]:
df_sort.head()

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
32860,2020-11-08 05:30:01,614304,Twitter for iPhone,1024658968394625024,\xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3,\xe3\x85\xa4\xe3\x82\xa2\xe3\x82\xa4\xe3\x82\x...,62,115,NaN,False,https://t.co/cHZdP4uOdu,"RT @JoeBiden: America, I\xe2\x80\x99m honored ...",140
33262,2020-11-07 21:52:54,581097,Twitter for Android,1099388669448867842,Neet\xf0\x9f\x83\x8fPeet,\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\x...,11,141,NaN,False,NaN,"RT @KamalaHarris: We did it, @JoeBiden. https:...",63
35111,2020-11-06 14:20:33,381458,Twitter Web App,2578241503,\xe3\x81\xaf\xe3\x81\xaa\xe3\x81\x91\xe3\x81\x...,Kei|20\xe2\x86\x91|intp|eng/fil OK|SparQlew\xe...,624,527,read carrd before follow!!,False,https://t.co/XgmHbPUgAi,RT @GretaThunberg: So ridiculous. Donald must ...,140
32585,2020-11-08 07:19:02,204348,Twitter for iPhone,1103362192169189376,Parneet kaur,"\xf0\x9f\x96\x95 all negative , all positive v...",587,193,"New Jersey, USA",False,https://t.co/PXgYJf0gIA,RT @Al_Sanchino: It\xe2\x80\x99s wild Trump su...,140
38044,2020-11-04 18:19:13,192350,Twitter for iPhone,54249914,Couture_Neet,snapchat . Neetsobeautiful,547,1182,Miii Casaa,False,NaN,"RT @JoeBiden: Keep the faith, guys. We\xe2\x80...",57

In [8]:
df_sort.value_counts()

created_at           retweet_count  source               user_id              user_name             user_description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user_follower_count  user_friends_count  user_location              user_verified  user_url                 tweet                                                                                                                                                                                                                 length_of_tweet
2020-10-31 06:33:58  0              Twitter Web App      1024167470230331393  Edumateplus           Your Success buddy for JEE, NEET Entrance exam                                                                                                                                                                                                                                                                                                                                                                                                                                                                      15                   2                   Navi Mumbai, India         False          https://t.co/8i4QZrfI1P  It's Quiz Time.\xe2\x8f\xb0\nComment Down Your Answer Below \xf0\x9f\x91\x87\xf0\x9f\x91\x87\n#JEE #NEET #MHTCET #EdumatePlus #Chemistry https://t.co/i8QEdQfxVQ                                                      117                4
2020-10-31 03:30:05  0              SocialBee.io v2      1143154191621165062  NeetGiSurgery         Your path to success for Mch/DNB Gi Surgery & Oncosurgery                                                                                                                                                                                                                                                                                                                                                                                                                                                           41                   2                   Ahmadabad City, India      False          https://t.co/YO2nxpx5hZ  \xf0\x9f\x92\x81\xe2\x80\x8d\xe2\x99\x80\xef\xb8\x8fDownload the app here: https://t.co/ZWz5SF5rkS\n\n\xe2\x9c\x85For more information visit: https://t.co/dzgnkDNhtd\n\n#SSGURU\xe2\x80\xa6 https://t.co/gWLGD9l3Q8  138                4
2020-10-31 00:49:56  0              twittbot.net         847203686            C-NEET International  Labors are the running dog of capitalism. NEET is a lonely warrior. We are the heart and soul of the world's NEET. Comrades, it's the time to unite together.                                                                                                                                                                                                                                                                                                                                                       116                  22                  In front of my desktop PC  False          https://t.co/ehT83J78eC  The stagment of capitalism caused by the surplus production changes dramatically the by the rise of non-productive people called "NEET".                                                                              136                4
2020-10-30 15:38:30  0              Twitter for iPhone   283556478            NewsFirst             XnewsFirst News & information to the Tamil viewers. Please follow up page to watch live and breaking news with latest Trending Matters adding every hour.                                                                                                                                                                                                                                                                                                                                                           114                  243                 Dindigul, India            False          https://t.co/RUZB00OK8P  After govt takes executive route, Tamil Nadu governor assents to 7.5% NEET quota Bill  #NEETReservation #EPS\xe2\x80\xa6 https://t.co/Yu4bUb46NT                                                                      133                4
2020-10-30 15:53:05  0              Twitter for Android  1026239606491107328  ajae                  spl2 fa / wannabe designer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          24                   26                  by myself                  False          https://t.co/fD5jZK1fuH  @YonoSSB @Neet_O_ @NairoMK This is my literal thought whenever this kind of stuff happens. I am 8000 percent with you on that                                                                                         125                4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ..
2020-10-29 16:57:01  145            Twitter for Android  4543390574           Abhimanyu Gupta       Nation First\xf0\x9f\x9a\xa9 | Staunch Indian \xf0\x9f\x9a\xa9|\xf0\x9f\x87\xae\xf0\x9f\x87\xb3| Pet Lover\xf0\x9f\x90\x95\xe2\x80\x8d\xf0\x9f\xa6\xba | \n\xe0\xa4\x89\xe0\xa4\xa4\xe0\xa5\x8d\xe0\xa4\xa4\xe0\xa4\xae \xe0\xa4\xac\xe0\xa4\xa8\xe0\xa5\x8b, \xe0\xa4\xb6\xe0\xa5\x8d\xe0\xa4\xb0\xe0\xa5\x87\xe0\xa4\xb7\xe0\xa5\x8d\xe0\xa4\xa0 \xe0\xa4\x96\xe0\xa5\x81\xe0\xa4\xa6 \xe0\xa4\xac\xe0\xa4\xa8 \xe0\xa4\x9c\xe0\xa4\xbe\xe0\xa4\x93\xe0\xa4\x97\xe0\xa5\x87 \xe0\xa5\xa4\xe2\x80\x8c\xe2\x80\x8c  305                  347                 Patna, Bihar, Hindustan    False          https://t.co/xlVLhGUFiW  RT @OpIndia_com: Yogi Adityanath asks chief secretary to write to NTA asking for Akanksha Singh to be declared topper with Soyeb Aftab in N\xe2\x80\xa6                                                               140                1
2020-10-29 16:55:49  145            Twitter Web App      47874909             Aditya Zaveri         Entrepreneur,Honoured To Be Followed By Our Beloved PM Shri @narendramodi                                                                                                                                                                                                                                                                                                                                                                                                                                           21296                5876                Gujarat, India             False          https://t.co/1I6UVp89HN  RT @OpIndia_com: Yogi Adityanath asks chief secretary to write to NTA asking for Akanksha Singh to be declared topper with Soyeb Aftab in N\xe2\x80\xa6                                                               140                1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        21295                5875                Gujarat, India             False          https://t.co/1I6UVp89HN  RT @OpIndia_com: Yogi Adityanath asks chief secretary to write to NTA asking for Akanksha Singh to be declared topper with Soyeb Aftab in N\xe2\x80\xa6                                                               140                1
2020-10-29 16:55:39  0              Twitter for Android  1218756658899251200  NEERAJ SONI           tweet retweet repeat .                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              536                  356                 twitter                    False          https://t.co/zs1w3lgOqh  @a_s_healer @Brownsk12 I am \xc3\xa0lsi a neet aspirant that's why I said                                                                                                                                             66                 1
2020-11-08 13:11:04  0              Paper.li             53490891             John J Zettel         I am a Transcendental Meditation Program Teacher - Enthusiast finding Species Universe or the Ultimate Missing Link by Solving the Quantum Conundrum!                                                                                                                                                                                                                                                                                                                                                               678                  1517                Milwaukee, WI              False          http://t.co/3zFWqXxbm0   NEET 2021: Syllabus, Books And Preparation Strategy For Chemistry https://t.co/FHRVse9GKw #physics                                                                                                                    98                 1
Name: count, Length: 6258, dtype: int64

In [9]:
highest_retweet = df_sort.iloc[0]
df_sort[["source", "retweet_count", "user_name", 
                 "tweet", "created_at", "user_url"]].head(1)

,source,retweet_count,user_name,tweet,created_at,user_url
32860,Twitter for iPhone,614304,\xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3,"RT @JoeBiden: America, I\xe2\x80\x99m honored ...",2020-11-08 05:30:01,https://t.co/cHZdP4uOdu

In [10]:
top10= df_sort.head(10)
top10_sum=top10["retweet_count"].sum()
(f"TOP 10 Retweet sum is {top10_sum}")

'TOP 10 Retweet sum is 2652225'

In [11]:
android = dff[dff["source"] == "Twitter for Android"]

print("Total Tweets from Twitter for Android:", android.shape[0])
print("Total Retweet Sum from Twitter for Android:", android["retweet_count"].sum())

Total Tweets from Twitter for Android: 28850
Total Retweet Sum from Twitter for Android: 9386742

In [12]:
highest_followers=dff.loc[dff["user_follower_count"].idxmax()]

In [13]:
highest_followers

created_at                                           2020-11-01 10:49:41
retweet_count                                                         15
source                                    Twitter Media Studio - LiveCut
user_id                                                         37034483
user_name                                                           NDTV
user_description       Breaking news alerts from India.\n\nInstagram:...
user_follower_count                                             13934355
user_friends_count                                                    15
user_location                                                      India
user_verified                                                       True
user_url                                         https://t.co/6yvEvvCmQi
tweet                  #Watch | Farmer's son Anil Kumar secures 77th ...
length_of_tweet                                                      123
Name: 44355, dtype: object

In [14]:
print("Username:", highest_followers["user_name"])
print("Location:", highest_followers["user_location"])

Username: NDTV
Location: India

In [15]:
dff["followers_friend_ratio"] = dff["user_follower_count"] / dff["user_friends_count"]

In [16]:
dff

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet,followers_friend_ratio
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.077778
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140,0.770819
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.281343
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.314775
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140,0.083333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56,0.495127
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74,0.030504
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140,1.000000
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140,0.106952
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139,0.355556

In [17]:
dff.isnull().sum()

created_at                    0
retweet_count                 0
source                       19
user_id                       0
user_name                     1
user_description          10871
user_follower_count           0
user_friends_count            0
user_location             21134
user_verified                 0
user_url                  38101
tweet                         0
length_of_tweet               0
followers_friend_ratio      147
dtype: int64

In [18]:
dff["user_description"].fillna("Twitter user", inplace=True)

/var/folders/7j/4mfq49jx199954g_vfv6fq_80000gn/T/ipykernel_27545/4020908461.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dff["user_description"].fillna("Twitter user", inplace=True)

In [19]:
dff

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet,followers_friend_ratio
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,Twitter user,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.077778
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140,0.770819
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.281343
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,Twitter user,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.314775
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140,0.083333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56,0.495127
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74,0.030504
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,Twitter user,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140,1.000000
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140,0.106952
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139,0.355556

In [20]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47381 entries, 0 to 47380
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   created_at              47381 non-null  object
 1   retweet_count           47381 non-null  int64
 2   source                  47362 non-null  object
 3   user_id                 47381 non-null  int64
 4   user_name               47380 non-null  object
 5   user_description        47381 non-null  object
 6   user_follower_count     47381 non-null  int64
 7   user_friends_count      47381 non-null  int64
 8   user_location           26247 non-null  object
 9   user_verified           47381 non-null  bool
 10  user_url                9280 non-null   object
 11  tweet                   47381 non-null  object
 12  length_of_tweet         47381 non-null  int64
 13  followers_friend_ratio  47234 non-null  float64
dtypes: bool(1), float64(1), int64(5), object(7)
memory usage: 4.7+ MB

In [21]:
dff.dropna(axis=1, inplace=True)

In [22]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47381 entries, 0 to 47380
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   created_at           47381 non-null  object
 1   retweet_count        47381 non-null  int64
 2   user_id              47381 non-null  int64
 3   user_description     47381 non-null  object
 4   user_follower_count  47381 non-null  int64
 5   user_friends_count   47381 non-null  int64
 6   user_verified        47381 non-null  bool
 7   tweet                47381 non-null  object
 8   length_of_tweet      47381 non-null  int64
dtypes: bool(1), int64(5), object(3)
memory usage: 2.9+ MB

In [23]:
dff.insert(2, "is_allow", True)

In [24]:
dff

,created_at,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,True,1250294694937915394,Twitter user,14,180,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,True,57059492,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,False,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,True,1016022678,"Wisdom is knowing the right path to take, Inte...",285,1013,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,True,1085818329816883201,Twitter user,147,467,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,True,1227501071490113537,it's not my attitude it's my style,2,24,False,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,True,1168840190426632192,Bhola sa chora,254,513,False,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,True,1696615807,Random person who likes drawing (but not a \nl...,23,754,False,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,True,1313330869113745413,Twitter user,2,2,False,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,True,1161551282995388416,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,False,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,True,1211810532006612992,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,False,i hate talking to people from my department bu...,139

In [25]:
dff.drop("tweet", axis=1, inplace=True)
dff.head()

,created_at,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,length_of_tweet
0,2020-10-31 14:10:28,141,True,1250294694937915394,Twitter user,14,180,False,139
1,2020-10-31 14:10:11,1,True,57059492,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,False,140
2,2020-10-31 14:09:48,141,True,1016022678,"Wisdom is knowing the right path to take, Inte...",285,1013,False,139
3,2020-10-31 14:09:41,141,True,1085818329816883201,Twitter user,147,467,False,139
4,2020-10-31 14:09:22,0,True,1227501071490113537,it's not my attitude it's my style,2,24,False,140

In [31]:
dff["created_at"]= dff["created_at"].astype(str)
dff["month"] = dff["created_at"].str.split("-").str[1]
dff["year"] = dff["created_at"].str.split("-").str[0]
dff[["month", "year"]]

      month  year
0        10  2020
1        10  2020
2        10  2020
3        10  2020
4        10  2020
...     ...   ...
47376    10  2020
47377    10  2020
47378    10  2020
47379    10  2020
47380    10  2020

[47381 rows x 2 columns]

In [29]:
dff.head()

,created_at,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,length_of_tweet,month,year
0,2020-10-31 14:10:28,141,True,1250294694937915394,Twitter user,14,180,False,139,10,2020
1,2020-10-31 14:10:11,1,True,57059492,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,False,140,10,2020
2,2020-10-31 14:09:48,141,True,1016022678,"Wisdom is knowing the right path to take, Inte...",285,1013,False,139,10,2020
3,2020-10-31 14:09:41,141,True,1085818329816883201,Twitter user,147,467,False,139,10,2020
4,2020-10-31 14:09:22,0,True,1227501071490113537,it's not my attitude it's my style,2,24,False,140,10,2020